# Generated by Django 3.2.25 on 2026-06-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_startaproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/featured/'),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
