# Generated by Django 3.2.25 on 2026-06-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20260614_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
