# Generated by Django 3.2.25 on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_project_is_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brands/')),
                ('scale', models.FloatField(default=1.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
