# Generated by Django 3.2.25 on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(
                choices=[
                    ('charge', 'Charge / Service'),
                    ('advance_paid', 'Advance Paid'),
                    ('remaining_due', 'Remaining Due'),
                ],
                default='charge',
                max_length=20,
            ),
        ),
    ]
