# Generated by Django 3.2.25 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_invoiceitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='hero_videos/posters/'),
        ),
    ]
